// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5YRIuG4LeGsouK2e7vFZxLJ1wnmua89g',
    appId: '1:244866013444:web:b95109880464ce93bdd851',
    messagingSenderId: '244866013444',
    projectId: 'zot-list',
    authDomain: 'zot-list.firebaseapp.com',
    storageBucket: 'zot-list.appspot.com',
    measurementId: 'G-9TGHEHLNVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI_wYk3vZpuUnxYEg-0K2uvqjeQuYAwgA',
    appId: '1:244866013444:android:59e2de46e6f69f16bdd851',
    messagingSenderId: '244866013444',
    projectId: 'zot-list',
    storageBucket: 'zot-list.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnOVF8uKMdRn-0SWlGDfvstewospdUkgc',
    appId: '1:244866013444:ios:be88586f61e268fcbdd851',
    messagingSenderId: '244866013444',
    projectId: 'zot-list',
    storageBucket: 'zot-list.appspot.com',
    iosClientId: '244866013444-smjdvq45phii6sfq2pq4dv6agvr10s86.apps.googleusercontent.com',
    iosBundleId: 'com.example.zotSell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnOVF8uKMdRn-0SWlGDfvstewospdUkgc',
    appId: '1:244866013444:ios:5937a5029e9fac9fbdd851',
    messagingSenderId: '244866013444',
    projectId: 'zot-list',
    storageBucket: 'zot-list.appspot.com',
    iosClientId: '244866013444-husg94mft6mpttse12gqfam94vpmm4b2.apps.googleusercontent.com',
    iosBundleId: 'com.example.zotSell.RunnerTests',
  );
}
